# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY
# See: https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0.1.11
_src_path: gh:hexdoc-dev/hexdoc-hexcasting-template
author: TechTastic
book_id: hexcasting:thehexbook
default_branch: master
github_repo: HexWeb
gradle_mod_version_key: mod_version
hexdoc_mod_plugin_classname: HexwebModPlugin
hexdoc_plugin_classname: HexwebPlugin
java_lang:
    ext: kt
    src: kotlin
java_package: io.github.techtastic.hexweb
mod_display_name: HexWeb
modid: hexweb
multiloader: true
package_export_root: doc/src/hexdoc_hexweb/_export
package_name: hexdoc-hexweb
package_slug: hexdoc_hexweb
package_src: doc/src/hexdoc_hexweb
pages_url: https://techtastic.github.io/HexWeb/
pattern_regex:
    per_world_value: 'true'
    regex: make\(\s*"(?P<name>[a-zA-Z0-9_\/]+)",\s*(?:new )?(?:ActionRegistryEntry|OperationAction)\(\s*HexPattern\.fromAngles\(\s*"(?P<signature>[aqweds]+)",\s*HexDir.(?P<startdir>\w+)\)
pattern_registry: casting/HexWebActions.kt
